root_folder = fileparts( mfilename('fullpath') );
addpath( fullfile(root_folder, 'chebfun') );
addpath( fullfile(root_folder, 'common') );
addpath( fullfile(root_folder, 'brock_mirman') );
addpath( fullfile(root_folder, 'rochet') );
addpath( fullfile(root_folder, 'brusan') );
addpath( fullfile(root_folder, 'brusan/log') );
addpath( fullfile(root_folder, 'TT-Toolbox/') );
addpath( fullfile(root_folder, 'TT-Toolbox/solve') );
addpath( fullfile(root_folder, 'TT-Toolbox//exp'));
addpath( fullfile(root_folder, 'TT-Toolbox/core'));
addpath( fullfile(root_folder, 'TT-Toolbox//cross'));
addpath( fullfile(root_folder, 'TT-Toolbox/misc'));
addpath( fullfile(root_folder, 'TT-Toolbox//fmex'));
addpath( fullfile(root_folder, 'TT-Toolbox/x/tests'));
addpath( fullfile(root_folder, 'TT-Toolbox//tt_regression'));
addpath( fullfile(root_folder, 'sglib'));