function out = sigmaXbs(x,param)

out = (x<=param.xstar) ...
        .* (  (Psi(x,param.Q(x),param) - x) ./ ( 1 - (Psi(x,param.Q(x),param)-x).*param.dQ(x)./param.Q(x) ) .* param.sigma ) ...
      + (x>param.xstar) ...
        .* (   (1 - x) ./ ( 1 - (1-x).*param.dQ(x)./param.Q(x) ) .* param.sigma   ) ;
    
end